# until somebody decides to wrap everything...
MD013: false

# repeating "New Features" etc. in separate top level blocks is ok
MD024:
  siblings_only: true

# we're fine with multiple top level headers
MD025: false
